# docker-compose.yml
version: '3.8'

services:
  rag-assistant:
    build: .
    ports:
      - "8501:8501"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./documents:/app/documents
      - ./chroma_db:/app/chroma_db